defaults: &defaults
  working_directory: ~/grafana-polystat-panel
  docker:
    - image: circleci/node:10.9.0-jessie

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build
          command: |
            yarn
            yarn global add grunt
            yarn global add jest
            node -p "require('node-sass').info"
            grunt
      - save_cache:
          key: v2-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
  grunttest:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test
          command: |
            yarn
            yarn global add grunt
            yarn add grunt
            grunt test

workflows:
  version: 2
  build-test:
    jobs:
      - build
