defaults: &defaults
  working_directory: ~/grafana-polystat-panel
  docker:
    - image: circleci/node:10.9.0-jessie

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: |
            yarn install
            sudo yarn add global grunt-cli
            sudo yarn add global jest
            #npm install -g grunt-cli
            #npm install -g jest
            node -p "require('node-sass').info"
            grunt
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  grunttest:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Test
          command: |
            yarn
            yarn global add grunt
            yarn add grunt
            grunt test

workflows:
  version: 2
  build-test:
    jobs:
      - build
